networks:
  odoo-net:
    driver: bridge

services:
  web:
    image: odoo19-local
    container_name: odoo19-server
    ports:
      - "8069:8069"
    volumes:
      - .:/workspace:Z
    command: python3 odoo-bin -c odoo.conf
    extra_hosts:
      - "host.containers.internal:host-gateway"
    networks:
      - odoo-net